---

- hosts: servers
  become: True

  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        create_home: yes
        state: present
        groups: sudo,docker
        append: yes
      loop: "{{ users }}"
      register: user_creation_result


    - name: Add SSH keys
      ansible.builtin.authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.key  }}"
      loop: "{{ users }}"


    - name: Allow user to execute sudo without password
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ item.name }}"
        content: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
        mode: '0440'
        owner: root
        group: root
        validate: /usr/sbin/visudo -cf %s
      loop: "{{ users }}"
